[
    {
        "id": 298028063,
        "name": "CVE-2014-0472",
        "full_name": "christasa\/CVE-2014-0472",
        "owner": {
            "login": "christasa",
            "id": 35037256,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/35037256?v=4",
            "html_url": "https:\/\/github.com\/christasa",
            "user_view_type": "public"
        },
        "html_url": "https:\/\/github.com\/christasa\/CVE-2014-0472",
        "description": "CVE-2014-0472 Django unexpected code execution using reverse()",
        "fork": false,
        "created_at": "2020-09-23T16:21:57Z",
        "updated_at": "2024-03-22T05:27:46Z",
        "pushed_at": "2020-12-24T08:12:32Z",
        "stargazers_count": 7,
        "watchers_count": 7,
        "has_discussions": false,
        "forks_count": 1,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 1,
        "watchers": 7,
        "score": 0,
        "subscribers_count": 1
    }
]